kind: Service
apiVersion: v1
metadata:
  name: back
  namespace: chaos-engineering
  labels:
    service: back
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8002
    targetPort: 8002
  selector:
    service: back