kind: Service
apiVersion: v1
metadata:
  name: front
  namespace: chaos-engineering
  labels:
    service: front
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    service: front