kind: Deployment
apiVersion: apps/v1
metadata:
  name: middle
  namespace: chaos-engineering
spec:
  replicas: 1
  selector:
    matchLabels:
      service: middle
  template:
    metadata:
      name: middle
      labels:
        name: middle
        app: middle
        service: middle
    spec:
      nodeSelector:
        app_group: chaos-engineering
      containers:
      - image: chaostoolkit/middle
        name: middle
        command: ["sh"]
        # fake a slow app
        args: ["-c", "sleep 10s; uvicorn --host 0.0.0.0 --port 8001 app:app"]
        ports:
        - containerPort: 8001
          protocol: TCP
          name: http
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 12
          periodSeconds: 5
        resources:
          limits:
            cpu: "200m"
            memory: 64Mi
          requests:
            cpu: "100m"
            memory: 64Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1